/* Unified Trust Anchor API Rust Wrapper
*
* This code includes the low-level C-bindings generated by bindgen and
* suppresses some warnings caused by naming conventions.
*
* Copyright (c) Siemens Mobility GmbH, 2025
*
* Authors:
*    Christian P. Feist <christian.feist@siemens.com>
*    Hermann Seuschek <hermann.seuschek@siemens.com>
*
* This work is licensed under the terms of the Apache Software License
* 2.0. See the COPYING file in the top-level directory.
*
* SPDX-License-Identifier: Apache-2.0
*/
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// NOTE: Handling unsigned 128 bit integers is not stable yet!
// Be careful, the interface could break in future!
#![allow(improper_ctypes)]

// Here we include the libuta bindings generated by bindgen
include!(concat!(env!("OUT_DIR"), "/bindgen_bindings.rs"));

