#
# Copyright (c) Siemens Mobility GmbH, 2022
#
# Author: Thomas Zeschg <thomas.zeschg@siemens.com>
#
# This work is licensed under the terms of the Apache Software License 
# 2.0. See the COPYING file in the top-level directory.
#
# SPDX-License-Identifier: Apache-2.0
#

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test_uta_sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./bootstrap
          ./configure HARDWARE=UTA_SIM --enable-tools
          make
      - name: Test
        run: |
          export LD_LIBRARY_PATH="$(pwd)/src/lib/.libs/"
          ./src/tools/uta_reg_test/.libs/uta_reg_test  

  test_tpm_ibm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install TPM Simulator
        run: |
          wget https://jaist.dl.sourceforge.net/project/ibmswtpm2/ibmtpm1682.tar.gz
          mkdir tpm_simulator
          cd tpm_simulator
          tar -xf ../ibmtpm1682.tar.gz
          cd src
          make
          ./tpm_server &
      - name: Install IBM TSS
        run: |
          sudo apt-get update
          sudo apt-get install -y libtss0 libtss-dev tss2
          sudo mkdir -p /var/lib/tpm_ibm
      - name: TPM Provisioning with random keys
        run: |
          export TPM_SIMULATOR=1
          ./src/provisioning/tpm_ibm/provisioning.sh
      - name: Build
        run: |
          ./bootstrap
